# -*- coding: utf-8 -*-
"""api-com-flask

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11kAobyUs_YqvanfrroU4LyFO6Qpbv4QJ
"""

!pip install Flask==3.0.0 pyngrok==7.1.2

from pyngrok import ngrok

from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/index')
def index():
    # Exemplo de dados em JSON
    data = [
        {"number": 1, "name": "rafael", "age": 25, "city": "rj", "country": "br"},
        {"number": 2, "name": "pedro", "age": 19, "city": "sp", "country": "br"},
        {"number": 3, "name": "jhon", "age": 18, "city": "sp", "country": "br"},
        {"number": 4, "name": "lucas", "age": 29, "city": "bh", "country": "br"},
        {"number": 5, "name": "bruno", "age": 30, "city": "mg", "country": "br"},
    ]

    return jsonify(data)

if __name__ == '__main__':
    app.run(debug=True)